### ISSUE TITLE
I am no longer able to change a subtask name in 1.9.0

### ISSUE THREAD

**Issue by AFCMS** [iman-salmani/iplan#52] opened 2023-07-17 04:42 UTC
When creating or modifying a sub task in 1.9.0 the name can be changed in the popup, but when exiting the popup nothing gets applied. The description change is applied.

I am getting no logs when running from terminal.

**Comment by iman-salmani** [comment] 2023-07-17 05:16
This is already fixed. #51
There are other issues that need to be fixed if I see they take some time, 1.9.1 will be released before them.
Sorry about that. I should do more tests before release.

**Comment by iman-salmani** [comment] 2023-07-17 05:18
Duplicate of #51

**Closed by iman-salmani** 2023-07-17 05:18 UTC
